### PR TITLE
Custome extension for proj file

### PR DESCRIPTION
**Pull request by ArseniySavin**
Added feature for setting mask file. added icon for task explorer and setting menu.
When is need using another extension for search the proj file with custom extension.

### CODE REVIEW

**Comment by Serg046** [comment]
1. There is already settings system, Settings.settings file is not required.
2. There is already app's icon `Icon.png`, BuildQueue_16x.png is not required.
3. I prefer to have Settings button inside the main window of Add-in instead of VS menu to not litter user's VS. I believe one button `MsBuild Task Explorer` is enough. We can put Settings button near the Refresh button.
4. New TaskExplorerSettingControl is base on Windows Forms technology but the main window is based on WPF. We need to choose one UI system and I prefer WPF.
5. New TaskExplorerSettingControl doesn't support Dark Visual Studio theme.

Possibly there are some notes regarding the code but for now I want you to fix 5 notes above first.
Thank you for your contribution.

**Comment by Serg046** [comment]
@ArseniySavin, I see there is yours [activity](https://github.com/Serg046/MsBuildTaskExplorer/commit/3ce18d39a08451ff03e9618a6922879fbcc2ba05) in this repo some hours ago.
Do you have a chance to take a look on my notes regarding the current PR?

**Comment by Serg046** [comment]
Modified, merged and released as version 1.3.3

**Comment by ArseniySavin** [comment]
Serg046 sorry. I litter that I was gone almost for a year. I did not have the opportunity to do anything. Are the comments that are relevant to correct?
I do not sign well with WPF, but can try.
As for the code, it is ready for any criticism and recommendations.

Serg046, I really apologize, really could not even answer.

**Comment by Serg046** [comment]
Np :)
I've already applied all the comments

**Comment by ArseniySavin** [comment]
Serg046 are the best. Thanks for your extension. Once again, I apologize.

**Pull request merged**
